server:
  servlet:
    context-path: /service1

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
